### ISSUE TITLE
0.1.0 Roadmap

### ISSUE THREAD

**Issue by phrb** [phrb/StochasticSearch.jl#1]
These are the intended features for **v0.1.0**:
- [x] Provide building blocks for the implementation of common Stochastic Local Search algorithms. 
  - [x] First Improvement
  - [x] Iterative First Improvement
  - [x] ~~Best Improvement~~ (pushed to **v0.1.x**)
  - [x] ~~Iterative Best Improvement~~ (pushed to **v0.1.x**)
  - [x] ~~Randomized Best Improvement~~ (pushed to **v0.1.x**)
  - [x] Random Walk
  - [x] Randomized First Improvement
  - [x] Probabilistic Iterative Improvement
  - [x] Greedy Construction
  - [x] Iterative Greedy Construction
  - [x] Simulated Annealing (rewrite with building blocks)
  
  Check: [Stochastic Local Search Algorithms: An Overview](http://link.springer.com/chapter/10.1007/978-3-662-43505-2_54#)
- [x] Independent measurement module.
  
  The measurement module should provide values of the user-defined function with a given configuration. Computational resources should be distributed between measurements. (see #4)
  - [x] `measure_mean!`: Uses `remotecall_fetch` to get results from multiple workers.
  - [x] ~~`sequential_measure_mean!`: Sequentially obtain results from a single worker.~~ (pushed to **v0.1.x**)
- [x] Independent search module.
  
  Stochastic Local Search techniques should execute independently, and request results from the measurement module.
- [x] Tests pass in Julia stable (**v0.3.x**).
- [x] Tests pass in Julia latest (**v0.4**).
