### ISSUE TITLE
0.4 Roadmap

### ISSUE THREAD

**Issue by phrb** [phrb/StochasticSearch.jl#21]
**Maintenance**:
- [x] Extract Duplicated Code (#27,)
- [x] Move to Julia **nightly** until **1.0**
- [x] Fix #28
- [x] Use Base.Test in all tests (#23)

**API Features**:
- [ ] Cluster managers (#15)
- [ ] A 'tuning run manager' to coordinate multiple runs
- [ ] Results logging and graphing utilities
- [ ] 'Cleanup' and 'startup' callback functions

**SLS Features**:
- [ ] More SLS techniques (#22)
- [ ] Option to split search space between technique instances
- [ ] Parameters should store a normalized value (#24)
- [ ] Perturbation functions should only modify normalized values (#25)
- [ ] Support for "conditional parameters" (#26)
