### ISSUE TITLE
0.3.0 Roadmap

### ISSUE THREAD

**Issue by phrb** [phrb/StochasticSearch.jl#8]
SLS techniques (moved to **v0.3.x** #21):
- [ ] ~~Best Improvement~~
- [ ] ~~Iterative Best Improvement~~
- [ ] ~~Randomized Best Improvement~~
- [x] Iterated Local Search
- [ ] ~~Dynamic Local Search~~
- [ ] ~~Tabu Search~~
- [ ] ~~Ant Colony Optimization~~

Features:
- [x] `PermutationParameter`
- [x] `neighbor!` for `PermutationParameter`
- [x] `perturb!` for `PermutationParameter`
- [x] `sequential_measure_mean!`: Obtain results sequentially, from a single worker.
- [x] Techniques run in different workers
- [x] ~~Support **v0.5**.~~

Supporting **v0.5** and abandoning **v0.4**:
- [x] Rename `RemoteRef`s ~> `RemoteChannel`s
- [x] Fix `remotecall` signature
- [x] Rewrite constructors
